[package]
name = "acrylic"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["everything"] }
raw-window-handle = "0.3.3"
lazy_static = "1.4.0"